artifact_location: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0
creation_time: 1734457007743
experiment_id: '0'
last_update_time: 1734457007743
lifecycle_stage: active
name: Default
