artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/f456604c311a48259f4491ce8fb72408/artifacts
end_time: 1734458164387
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f456604c311a48259f4491ce8fb72408
run_name: Default
run_uuid: f456604c311a48259f4491ce8fb72408
source_name: ''
source_type: 4
source_version: ''
start_time: 1734458164378
status: 3
tags: []
user_id: mle-user
